config/routes.rb
Rails.application.routes.draw do

  root('application#home', {as: 'home'})
  get('/recommended', {to: 'application#recommended', as: 'recommended'})
  resources :users, only: [:new, :create, :show, :update, :destroy]
  get('/workstyle', {to: 'users#workstyle'})
  get('/playstyle', {to: 'users#playstyle'})
  get('/personality', {to: 'users#personality'})
  resources(:languages, only: [:new, :create, :show, :update, :destroy])
  resources(:editors, only: [:new, :create, :show, :update, :destroy])
  resources(:companies, only: [:new, :create, :show, :update, :destroy])
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/companies_language.rb
class CompaniesLanguage < ApplicationRecord
  belongs_to :company
  belongs_to :language
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :companies_languages
  has_many :languages, through: :companies_languages

  def self.culture_companies
    Company.all.select do |company|
      company.culture > 7.5
    end
  end

  def self.work_life_companies
    Company.all.select do |company|
      company.worklife > 7.5
    end
  end

  def self.compensation_companies
    Company.all.select do |company|
      company.compensation > 7.5
    end
  end

end

app/models/editor.rb
class Editor < ApplicationRecord
  has_many :languages_editor
  has_many :languages, through: :languages_editor


    
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :companies_languages
  has_many :companies, through: :companies_languages

  has_many :languages_editor
  has_many :editors, through: :languages_editor
end

app/models/languages_editor.rb
class LanguagesEditor < ApplicationRecord
  belongs_to :language
  belongs_to :editor
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def complete_personality_score
    self.response_one_personality
    self.response_two_personality
    self.response_three_personality
  end

  def response_one_personality
    if self.response_one == 'Culture'
      self.personality_score += 1
    elsif self.response_one == 'Work-Life Balance'
      self.personality_score += 5
    elsif self.response_one == 'Compensation'
      self.personality_score += 10
    end
  end

  def response_two_personality
    if self.response_two == 'Spiderman'
      self.personality_score += 1
    elsif self.response_two == 'Superman'
      self.personality_score += 5
    else self.response_two == 'Batman'
      self.personality_score += 10
    end
  end

  def response_three_personality
    if self.response_three == 'Froot Loops'
      self.personality_score += 1
    elsif self.response_three == 'Frosted Flakes'
      self.personality_score += 5
    elsif self.response_three == 'Lucky Charms'
      self.personality_score += 10
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
   @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
   current_user.id != nil
  end

  def require_logged_in
   return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end

  def home
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController


end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController

  def index
    @editors = Editor.all
  end

  def show
    @editor = Editor.find(params[:id])
  end

  def new
    @editor = Editor.new
  end

  def create
    @editor = Editor.new(editor_params)
    if @editor.save
      redirect_to editor_path(@editor)
    else
      render :new
    end
  end
  
  private

  def editor_params
    params.require(:editor).permit(:name, :date_created, :latest_version, :creator, :short_description)
  end

end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @languages = Language.all
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to language_path(@language)
    else
      render :new
    end
  end

  def show
    @language = Language.find(params[:id])
  end

  private

  def language_params
    params.require(:language).permit(:name, :date_created, :latest_version, :creator, :short_description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(user_name: params[:user][:user_name])

    user = user.try(:authenticate, params[:user][:password])


    return redirect_to(controller: 'sessions', action: 'new') unless user

    session[:user_id] = user.id

    @user = user


    redirect_to user_path(@user)

  end

  def destroy
    session.delete :user_id

    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    return redirect_to new_user_path unless @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
    @languages = []
    @companies = []

    if session[:user_id] != @user.id
      redirect_to home_path
    end

    @user.complete_personality_score

    if @user.personality_score == 3 || @user.personality_score == 7 || @user.personality_score == 12
      Company.culture_companies.each do |company|
        @companies << company.name
      end
    elsif @user.personality_score == 11 || @user.personality_score == 15 || @user.personality_score == 20
      Company.work_life_companies.each do |company|
        @companies << company.name
      end
    elsif @user.personality_score == 21 || @user.personality_score == 25 || @user.personality_score == 30
      Company.compensation_companies.each do |company|
        @companies << company.name
      end
    else
      @companies << Company.all.sample.name
    end


    Language.all.each do |l|
      l.companies.each do |c|
        if @user.company == c.name && l.dev_type == @user.dev_type
          @languages << l
        end
      end
    end

  end

  def workstyle
    @user = current_user
    @companies = []

    Company.all.each do |company|
      @companies << company.name
    end
  end

  def playstyle
    @user = current_user
  end

  def personality
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to(user_path(@user))
    else
      render(:workstyle)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_name, :company, :password, :dev_type, :password_confirmation, :personality_score, :response_one, :response_two, :response_three)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.erb
<div class="jumbotron jumbotron-fluid" style='text-align:center'>
  <div class="container">
    <h1 class="display-3" style ='font-family:NTR ;'>THE STRUGGLE IS REAL</h1>
    <p class="lead">Sometimes, we need a little help . . .</p>
  </div>
</div>



  <div class='container'>

    <div class='row' style='margin:30px 0px -10px 0px ;'>

      <div class='col-6' style='border-style:solid; border-left:0;border-top:0;border-bottom:0;'>
        <h2 style='text-align:center; font-family:yantramanav'>Why You Are Here</h2>
        <p>
          Picking up programming can be an overwhelming feat, especially when choosing a language! We understand, and want to help. The secret is, most modern programming languages are capable of the same things! When you hear the phrase, it all comes down to ones and zeros, that isn't too far off. It comes down to you, your workstyle, and your playstyle. You don't have to make this unecessarily challenging decision on your own. Welcome to TheStruggle!
        </p>

      </div>

      <div class='col-6'>
        <h2 style='text-align:center;font-family:yantramanav'>Why We Are Here</h2>
        <p>
        TheStruggle is your personal guide to understanding the where you fit in the programming landscape. Start off by creating a profile and answering a few questions! From there we will use our top-secret algorithm to determine which programming languages, tech-companies, and tech-events you should be aware of. Of course this is all based on our passionate and well studied opinion . . . But don't fret, we tend to have good ones.
        </p>

      </div>
    </div>
  </div>




<div style='text-align:center; margin-top:60px'>
  <div style='margin:0 0 60 0 ;font-family:yantramanav;'>
    <h1 style='font-family:yantramanav; font-weight:900; margin-bottom:30px;'>LANGUAGES</h1>
  </div>

  <!-- Language List -->
  <div class="container" >
    <div class="row" style='background-color:#E4E7EB; border-style:solid; border-color:#A9A9A9'>
      <% Language.all.each_with_index do |language, i| %>
      <div class="col-3" style='padding:50px;'>
        <div ><%= link_to(image_tag("#{language.name.downcase}100.png", size: '75x75') , language_path(language.id)) %></div>
        <div ><h3><%= link_to(language.name, language_path(language.id)) %></h3></div>
        <div ><h6><%=language.short_description%></h6>
        </div>
      </div>
      <% end %>
    <div class="w-100"></div>
  </div>

</div>

app/views/application/home.html.erb
<h1>Welcome to The Struggle</h1>


<%=link_to "View All Editors", editors_path%>

<%=link_to "View All Languages", languages_path%>

app/views/companies/show.erb
<h1>Test</h1>

app/views/editors/edit.erb
<%= link_to('Home', home_path) %>

app/views/editors/index.erb
<%= link_to('Home', home_path) %>

<% @editors.each do |editor| %>
<%=   link_to(editor.name, editor_path(editor)) %> <br />
<% end %>

app/views/editors/index.html.erb
<h1>List of IDE's</h1>

<%@editors.each do |e|%>
  <label>Name: </label>
  <%=link_to e.name, editor_path(e)%><br>
<%end%>

app/views/editors/new.erb
<%= link_to('Home', home_path) %>

app/views/editors/show.erb
<div style='padding-top:50px'>

      <div style='text-align:center; font-family:questrial;'>
        <% if File.file?("app/assets/images/#{@editor.name.downcase}100.png")%>
        <%= (image_tag("#{@editor.name.downcase}100.png")) %>
        <% else %>
        <%= (image_tag("default100.png")) %>
        <% end %>
        <h4 style ='font-size:100px;'><%=@editor.name%></h4>


      <div style='margin-top:100px; text-align:left;'>

      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Year Created:</h4>   <h6 style ='font-size:15px; font-style:bold; padding-left:30px;';><%=@editor.date_created%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Latest Version:</h4> <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@editor.latest_version%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Creator:</h4>        <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@editor.creator%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Description:</h4>    <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@editor.short_description%></h6>
      </div>
    </div>
  </div>
</div>

app/views/editors/show.html.erb
<label>Name: </label>
<%=@editor.name%><br>

<label>Date Created: </label>
<%=@editor.date_created%><br>

<label>Latest Version: </label>
<%=@editor.latest_version%><br>

<label>Creator: </label>
<%=@editor.creator%><br>

<label>Short Description: </label>
<%=@editor.short_description%><br>

app/views/languages/edit.erb
<%= link_to('Home', home_path) %>

app/views/languages/index.erb
<%= link_to('Home', home_path) %>

<% @languages.each do |language| %>
<%= link_to(language.name, language_path(language)) %> <br />
<% end %>

app/views/languages/index.html.erb
<h1>List of Languages</h1>

<%@languages.each do |l|%>
  <label>Name: </label>
  <%=link_to l.name, language_path(l)%><br>
<%end%>

app/views/languages/new.erb
<%= link_to('Home', home_path) %>

app/views/languages/show.erb
<div style='padding-top:50px'>

      <div style='text-align:center; font-family:questrial;'>
        <%= image_tag("#{@language.name.downcase}100.png") %>
        <h4 style ='font-size:100px;'><%=@language.name%></h4>


      <div style='margin-top:100px; text-align:left;'>

      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Year Created:</h4>   <h6 style ='font-size:15px; font-style:bold; padding-left:30px;';><%=@language.date_created%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Latest Version:</h4> <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@language.latest_version%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Creator:</h4>        <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@language.creator%></h6>
      <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Description:</h4>    <h6 style ='font-size:15px; font-style:bold; padding-left:30px;'><%=@language.short_description%></h6>
      </div>
    </div>
  </div>

<div style='margin: 100px 0 0 0 ;font-family:yantramanav;text-align:center;'>
<h1 style='padding:0 0 100px 0px; font-weight:900;'>RECOMMENDED IDE's</h1>

<div class="container">
  <div class="row" style='background-color:#E4E7EB; border-style:solid; border-color:#A9A9A9'>
      <%@language.editors.each do |editor|%>
      <div class="col-4" style='padding:50px; text-align:center'>
        <% if File.file?("app/assets/images/#{editor.name.downcase}100.png")%>
          <%=link_to(image_tag("#{editor.name.downcase}100.png"), editor_path(editor)) %>
        <% else %>
          <%=link_to(image_tag("default100.png"), editor_path(editor)) %>
        <% end %>
        <h3><%= link_to(editor.name, editor_path(editor))%></h3>
      </div>
      <%end%>

  </div>
</div>

app/views/languages/show.html.erb
<label>Name: </label>
<%=@language.name%><br>

<label>Date Created: </label>
<%=@language.date_created%><br>

<label>Latest Version: </label>
<%=@language.latest_version%><br>

<label>Creator: </label>
<%=@language.creator%><br>

<label>Short Description: </label>
<%=@language.short_description%><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheStruggle</title>
    <!-- Rails Config -->
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <link rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <!-- Bootstrap Config -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=NTR|Questrial|Yantramanav:100,400,900" rel="stylesheet">

  </head>




  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top" style='position:fixed; width:100%;'>
    <a class="navbar-brand" style='padding-top:10px' href="/"> <%=image_tag('logomini.png', size: '105x23') %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <%if session[:user_id]%>
        <li class="nav-item active">
          <a class="nav-link" href="<%=user_path(session[:user_id])%>">My Profile<span class="sr-only">(current)</span></a>
        </li>
        <% end %>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> -->
      </ul>
      <%if session[:user_id]%>
          <a class="nav-link disabled" href="/logout">Logout</a>
      <%else%>
          <a class="nav-link disabled" href="/login">Login</a>
          <a class="btn btn-dark" href="/users/new">Signup</a>
      <%end%>
      </div>
      </nav>
    </header>

    <!--  -->
    <div style="padding-top:50px">
      <%= yield %>
    </div>
    <!--  -->


    <!-- BootStrap Javascript Plugins -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <footer style='padding-top:8px; font-family:yantramanav;font-size:x-small;'>
      Made With <i class="em em-collision"></i> : <a href='https://www.asheaustaire.com'>@AsheAustaire</a> <a href=''>@AlArtesona</a>.
    </footer>
  </body>

</html>

app/views/users/new.erb
<div style="text-align:center; padding-top:50px;">

<h1>Create a User</h1>

<div>
<div style="text-align:center">


<%= form_for @user do |f| %>
  <div class="form-group float-center">
    <%= f.label :name, "Full Name", class: "col-md-4 control-label" %><br>
  <div class="col-md-3" style='display:inline-block;'>
    <%= f.text_field :name %>
  </div>
  </div>

  <div class="form-group float-center">
    <%= f.label :user_name, "Username", class: "col-md-4 control-label" %><br>
  <div class="col-md-3" style='display:inline-block;'>
    <%= f.text_field :user_name %>
  </div>
  </div>


  <div class="form-group">
    <%= f.label :password, "Password", class: "col-md-4 control-label" %><br>
  <div class="col-md-3" style='display:inline-block;'>
    <%= f.password_field :password %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-4 control-label" %><br>
  <div class="col-md-3" style='display:inline-block;'>
    <%= f.password_field :password_confirmation %>
  </div>
  </div>

  <%= f.submit "Create User", class: "btn btn-default btn-primary" %>
<% end %>



</div>

app/views/users/personality.erb
<div style='text-align:left; margin-top:150px'>

<div class='container'>
<%=form_for @user do |f|%>

  <h1 style=><%=f.label :response_one, "What is most important to you when looking to work for a company?"%></h1>
  <%=f.select :response_one, ['Culture', 'Work-Life Balance', 'Compensation'],{}, class: "btn btn-secondary dropdown-toggle btn-lg" %>

  <h1 style='margin-top:50px'><%=f.label :response_two, "Who is your favorite superhero?"%></h1>
  <%=f.select :response_two, ['Spiderman', 'Superman', 'Batman'],{}, class: "btn btn-secondary dropdown-toggle btn-lg" %><br><br>

  <h1 style='margin-top:50px'><%=f.label :response_three, "If you were a box of cereal, what cereal would you be?"%></h1>
  <%=f.select :response_three, ['Froot Loops', 'Frosted Flakes', 'Lucky Charms'],{}, class: "btn btn-secondary dropdown-toggle btn-lg" %><br><br>

  <%=f.submit class: "btn btn-success"%>
<%end%>

</div>

</div>

app/views/users/playstyle.erb
<div class='container'>
<div style='text-align:left; margin-top:150px'>
<%=form_for @user do |f|%>
  <h1><%=f.label :dev_type, "What type of developer are you?"%></h1>
  <%=f.select :dev_type, ['Front-End', 'Back-End'], {}, class: "btn btn-secondary dropdown-toggle btn-lg" %>

  <%=f.submit class: "btn btn-success"%>
<%end%>

</div>

app/views/users/show.erb
<div style='padding-top:100px'>

  <div class='container'>
    <div class='row' style='margin-bottom:40px'>
      <div class='col-6' style='text-align:center; font-family:questrial;'>
        <img style='border-radius:50%; border-style:solid' height="150" width="150" src='https://media.giphy.com/media/xT0GqxOURpu9mmaF7q/giphy.gif' />
        <h4 style='padding:10px 0 0 0 ; font-family:Yantramanav; font-weight:900'><%=@user.user_name%></h4>
      </div>

      <div class='col'>
        <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Name:</h4>
        <h6 style ='font-size:15px; font-style:bold; padding-left:30px;';><%=@user.name%></h6>

        <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Company Preference</h4>
        <h6 style ='font-size:15px; font-style:bold; padding-left:30px;';><%=@user.company%></h6>

        <h4 style ='font-size:30px; font-family:Yantramanav; font-weight:900; padding:0px 0px 0px 10px'>Developer Type</h4>
        <h6 style ='font-size:15px; font-style:bold; padding-left:30px;';><%=@user.dev_type%></h6>
        </div>
      </div>
    </div>
  </div>

  <div class='container' >
    <div class='row'>
      <div class='col-6' style='text-align:center; font-family:questrial;'>

        <h3 style='font-family:yantramanav; font-weight:900;'>
          RECOMMENDED LANGUAGES
        </h3>
            <h1>
              <%language = @languages.sample%>
              <%= image_tag("#{language.name.downcase}.png") %>
              <%= link_to(language.name, language_path(language.id))%>
            </h1>



        <h3 style='font-family:yantramanav; font-weight:900;'>
          RECOMMENDED COMPANIES
        </h3>
        <h1>
            <% company = @companies.sample %>
              <div style='font-family:questrial'>
            <%= image_tag("#{company.downcase}.png", size: "46x46")%>
              <%= company %>
            </div>
        </h1>
      </div>
      <div class='col-6'>
        <a class="btn btn-success btn-lg btn-block animated rubberBand" style='-webkit-animation-delay: 4s;-webkit-animation-duration: 3s; margin-bottom:12px;' href='/workstyle'>WORKSTYLE</a>
        <a class="btn btn-danger btn-lg btn-block animated rubberBand" style='-webkit-animation-delay: 14s;-webkit-animation-duration: 3s;margin-bottom:12px;' href='/playstyle'>PLAYSTYLE</a>
        <a class="btn btn-info btn-lg btn-block animated rubberBand" style='-webkit-animation-delay: 24s;-webkit-animation-duration: 3s;' href='/personality'>PERSONALITY</a>
      </div>
    </div>
  </div>
</div>

app/views/users/workstyle.erb
<div class='container'>
<div style='text-align:left; margin-top:150px'>
  <%= form_for @user do |f| %>
    <h1 style='font-family:questrial'>
      <%= f.label :company, "Which Company Would You Like To Work For?" %>
    </h1>
    <%=f.select :company, @companies,{}, class: "btn btn-secondary dropdown-toggle btn-lg" %>
    <%=f.submit class: "btn btn-success" %>
  <% end %>
</div>
</div>